export const ADD_PATIENT_REQUEST="ADD_PATIENT_REQUEST"
export const ADD_PATIENT_SUCCESS = "ADD_PATIENT_SUCCESS";
export const ADD_PATIENT_FAIL = "ADD_PATIENT_FAIL";
export const EDIT_PATIENT_REQUEST = "EDIT_PATIENT_REQUEST";
export const EDIT_PATIENT_SUCCESS = "EDIT_PATIENT_SUCCESS";
export const EDIT_PATIENT_FAIL = "EDIT_PATIENT_FAIL";
export const DELETE_PATIENT="DELETE_PATIENT"
export const RESET_DATA="RESET_DATA"